/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tuan5;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.security.MessageDigest;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class HamBam extends javax.swing.JFrame {

    /**
     * Creates new form HamBam
     */
    public HamBam() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtbam1 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtbam2 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtgoc = new javax.swing.JTextArea();
        txtuser = new javax.swing.JTextField();
        txtpass = new javax.swing.JTextField();
        bntSignIn = new javax.swing.JButton();
        bntRegister = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("HASH MD5");

        jLabel2.setText("Username:");

        jLabel3.setText("Password:");

        jLabel4.setText("Result 1:");

        txtbam1.setColumns(20);
        txtbam1.setRows(5);
        jScrollPane1.setViewportView(txtbam1);

        jLabel5.setText("Result 2:");

        txtbam2.setColumns(20);
        txtbam2.setRows(5);
        jScrollPane2.setViewportView(txtbam2);

        jLabel6.setText("String: Usernam + Pass");

        txtgoc.setColumns(20);
        txtgoc.setRows(5);
        jScrollPane3.setViewportView(txtgoc);

        bntSignIn.setText("SignIn");
        bntSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSignInActionPerformed(evt);
            }
        });

        bntRegister.setText("Register");
        bntRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntRegisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 46, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(bntSignIn)
                        .addGap(66, 66, 66)
                        .addComponent(bntRegister)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntSignIn)
                    .addComponent(bntRegister))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntRegisterActionPerformed
       try{
           String user = txtuser.getText();
           String pass = txtpass.getText();
           String bam = "";
           bam = user + pass;
           MessageDigest md = MessageDigest.getInstance("MD5");
           md.update(bam.getBytes());
           byte[] byteData = md.digest();
           StringBuffer sb = new StringBuffer();
           for(int i = 0; i < byteData.length; i++){
               sb.append(Integer.toString((byteData[i] & 0xff)+ 0x100, 16).substring(1));
           }
           System.out.println("Digest:: "+ sb.toString());
           txtbam1.setText(sb.toString());
           StringBuffer hexString = new StringBuffer();
           for(int i = 0; i < byteData.length; i++){
               String hex = Integer.toHexString(0xff & byteData[i]);
               if(hex.length()==1){
                   hexString.append('0');
               }
               hexString.append(hex);
           }
           System.out.println("Digest: "+hexString.toString());
           txtbam2.setText(hexString.toString());
           txtgoc.setText(bam.toString());
           BufferedWriter bw = null;
           String filename = "D:\\Bam.txt";
           bw = new BufferedWriter(new FileWriter(filename));
           bw.write(hexString.toString());
           bw.close();
           JOptionPane.showMessageDialog(null, "ban da dang ky thah cong");
       
           
       } catch (Exception ex){
           System.out.println("Loi bam user va pass"+ ex);
       }
        
        
    }//GEN-LAST:event_bntRegisterActionPerformed

    private void bntSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSignInActionPerformed
           String user = txtuser.getText();
           String pass = txtpass.getText();
           String bam = "";
           bam = user + pass;
           BufferedReader br = null;
           String filename = "D:\\Bam.txt";
            try{
                br = new BufferedReader(new FileReader(filename));
                StringBuffer sb = new StringBuffer();
                char[] ca = new char[5];
                while (br.ready()){
                    int len = br.read(ca);
                    sb.append(ca, 0, len);
                }
                br.close();
                System.out.println("chung thuc: "+" "+sb);
                String chuoi = sb.toString();
                MessageDigest md = MessageDigest.getInstance("MD5");
                md.update(bam.getBytes());
                byte[] byteData = md.digest();
                StringBuffer hexString = new StringBuffer();
                for(int i = 0; i < byteData.length; i++){
               String hex = Integer.toHexString(0xff & byteData[i]);
               if(hex.length()==1){
                   hexString.append('0');
               }
               hexString.append(hex);
            }
                System.out.println("Bam user va pass"+" "+hexString.toString());
                boolean k=hexString.toString().equals(chuoi);
                if(k==true){
                    JOptionPane.showMessageDialog(null, "dang nhap thanh cong");
                    txtbam1.setText(hexString.toString());
                    txtbam2.setText(chuoi);
                    txtgoc.setText("User name: "+ user+"Password: "+pass);
                    
                }
                else
                        JOptionPane.showMessageDialog(null, "dang nhap that bai");
            } catch (Exception ex){
                System.out.println("Loi dang nhap"+ ex);
            }
    }//GEN-LAST:event_bntSignInActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HamBam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HamBam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HamBam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HamBam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HamBam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntRegister;
    private javax.swing.JButton bntSignIn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea txtbam1;
    private javax.swing.JTextArea txtbam2;
    private javax.swing.JTextArea txtgoc;
    private javax.swing.JTextField txtpass;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
