package Tuan2;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.Cipher;
import javax.crypto.CipherInputStream;
import javax.crypto.CipherOutputStream;
import javax.crypto.SecretKey;
import javax.crypto.SecretKeyFactory;
import javax.crypto.spec.DESKeySpec;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class DES extends javax.swing.JFrame {

    /**
     * Creates new form DES
     */
    public DES() {
        initComponents();
    }
    private int mode;
    private static void doCopy(InputStream is,OutputStream os)throws IOException{
        byte[] bytes = new byte[64];
        int numBytes;
        while((numBytes = is.read(bytes)) != -1){
            os.write(bytes,0,numBytes);
        }
        os.flush();
        os.close();
        is.close();
    }
    public static void encrypt(String key,InputStream is,OutputStream os) throws Throwable {
        encryptOrDecrypt(key,Cipher.ENCRYPT_MODE,is,os);
    }
    public static void decrypt(String key,InputStream is,OutputStream os) throws Throwable {
        encryptOrDecrypt(key,Cipher.DECRYPT_MODE,is,os);
    }
    public static void encryptOrDecrypt(String key,int mode,InputStream is,OutputStream os) throws Throwable {
        DESKeySpec dks = new DESKeySpec(key.getBytes());
        SecretKeyFactory skf = SecretKeyFactory.getInstance("DES");
        SecretKey desKey = skf.generateSecret(dks);
        Cipher cipher  = Cipher.getInstance("DES");
        if(mode == Cipher.ENCRYPT_MODE)
        {
            cipher.init(Cipher.ENCRYPT_MODE,desKey);
            CipherInputStream cis = new CipherInputStream(is,cipher);
            doCopy(cis,os);
        }else if(mode == Cipher.DECRYPT_MODE)
        {
            cipher.init(Cipher.DECRYPT_MODE,desKey);
            CipherOutputStream cos = new CipherOutputStream(os,cipher);
            doCopy(is,cos);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        keybox = new javax.swing.JTextField();
        bntMaHoa = new javax.swing.JButton();
        btnhienthi = new javax.swing.JButton();
        bntGhiFile = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        plaintextbox = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ciphertextbox = new javax.swing.JTextArea();
        bntGiaiMa = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("DES");

        jLabel2.setText("Input Key");

        bntMaHoa.setText("Mã hóa");
        bntMaHoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntMaHoaActionPerformed(evt);
            }
        });

        btnhienthi.setText("Hiển thị");
        btnhienthi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhienthiActionPerformed(evt);
            }
        });

        bntGhiFile.setText("Ghi File");
        bntGhiFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntGhiFileActionPerformed(evt);
            }
        });

        jLabel3.setText("PlainText");

        plaintextbox.setColumns(20);
        plaintextbox.setRows(5);
        jScrollPane1.setViewportView(plaintextbox);

        jLabel4.setText("CipherText");

        ciphertextbox.setColumns(20);
        ciphertextbox.setRows(5);
        jScrollPane2.setViewportView(ciphertextbox);

        bntGiaiMa.setText("Giải Mã");
        bntGiaiMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntGiaiMaActionPerformed(evt);
            }
        });

        jButton5.setText("All Show");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(keybox, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(bntGiaiMa)
                        .addGap(36, 36, 36)
                        .addComponent(jButton5))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bntGhiFile)
                                .addGap(32, 32, 32)
                                .addComponent(bntMaHoa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnhienthi)
                                .addGap(19, 19, 19))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                                .addComponent(jScrollPane2)))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(keybox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntMaHoa)
                    .addComponent(btnhienthi)
                    .addComponent(bntGhiFile))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bntGiaiMa)
                            .addComponent(jButton5))
                        .addGap(14, 14, 14))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnhienthiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhienthiActionPerformed
        try{
            BufferedReader br = null;
            String filename = "D:\\EnDes.txt";
            br = new BufferedReader(new FileReader(filename));
            StringBuffer sb = new StringBuffer();
            JOptionPane.showMessageDialog(null, "Da Mo file");
            char[] ca = new char[5];
            while (br.ready()){
                int len = br.read(ca);
                sb.append(ca,0,len);
            }
            br.close();
            System.out.println("Du lieu la: "+" "+sb);
            String chuoi = sb.toString();
            plaintextbox.setText(chuoi);
        }catch(IOException ex){
            Logger.getLogger(DES.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_btnhienthiActionPerformed
    
    private void bntMaHoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntMaHoaActionPerformed
         try {
            String key = keybox.getText();
            FileInputStream fis = new FileInputStream("D:\\DeDes.txt");
            FileOutputStream fos = new FileOutputStream("D:\\EnDes.txt");
            encrypt(key,fis,fos);
            JOptionPane.showMessageDialog(null,"Da ma hoa van ban");
            /*String fileName = "D:\\EnDes.txt";
            BufferedReader br = null;
            br = new BufferedReader(new FileReader(fileName));
            StringBuffer sb = new StringBuffer();
            char[] ca = new char[5];
            while(br.ready())
            {
                int len = br.read(ca);
                sb.append(ca,0,len);
            }
            br.close();
            System.out.println("Du lieu la: " + " " + sb);
            String chuoi = sb.toString();
            ciphertextbox.setText(chuoi);*/
        }catch(Throwable e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_bntMaHoaActionPerformed

    private void bntGiaiMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntGiaiMaActionPerformed
                FileInputStream fis2 = null;
        try{
            String key = keybox.getText();
            fis2 = new FileInputStream("D:\\EnDes.txt");
            FileOutputStream fos2 = new FileOutputStream("D:\\DeDes.txt");
            decrypt(key,fis2,fos2);
            String fileName = "D:\\DeDes.txt";
            BufferedReader br = null;
            br = new BufferedReader(new FileReader(fileName));
            StringBuffer sb = new StringBuffer();
            JOptionPane.showMessageDialog(null,"Da gia ma");
            char[] ca = new char[5];
            while(br.ready())
            {
                int len = br.read(ca);
                sb.append(ca,0,len);
            }
            br.close();
            System.out.println("Du lieu la: " + " " + sb);
            String chuoi = sb.toString();
            ciphertextbox.setText(chuoi);
        }catch(Throwable ex)
        {
            Logger.getLogger(DES.class.getName()).log(Level.SEVERE,null,ex);
        }finally {
            try {
                fis2.close();
            }catch(IOException ex) {
                Logger.getLogger(DES.class.getName()).log(Level.SEVERE,null,ex);
            }
        }
    }//GEN-LAST:event_bntGiaiMaActionPerformed

    private void bntGhiFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntGhiFileActionPerformed
                try {
            BufferedWriter bw = null;
            String fileName = "D:\\DeDes.txt";
            String s = plaintextbox.getText();
            bw = new BufferedWriter(new FileWriter(fileName));
            bw.write(s);
            bw.close();
            JOptionPane.showMessageDialog(null,"Da ghi file");
            plaintextbox.setText(s);
        }catch(IOException ex){
            Logger.getLogger(DES.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_bntGhiFileActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new DES().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntGhiFile;
    private javax.swing.JButton bntGiaiMa;
    private javax.swing.JButton bntMaHoa;
    private javax.swing.JButton btnhienthi;
    private javax.swing.JTextArea ciphertextbox;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField keybox;
    private javax.swing.JTextArea plaintextbox;
    // End of variables declaration//GEN-END:variables
}
