package Tuan3;


import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.security.NoSuchAlgorithmException;
import java.util.Base64;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.Cipher;
import javax.crypto.KeyGenerator;
import javax.crypto.SecretKey;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */
public class AES extends javax.swing.JFrame {
    private SecretKey secretKey;
    private byte[] byteCipherText;
    private String strDecryptedText;
    
    public AES() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        aaaa = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        zzz = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtvanban = new javax.swing.JTextArea();
        txtkhoa = new javax.swing.JTextField();
        txtpass = new javax.swing.JTextField();
        txtuser = new javax.swing.JTextField();
        bntDangNhap = new javax.swing.JButton();
        bntDangKy = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtmahoa = new javax.swing.JTextArea();
        bntMaHoa = new javax.swing.JButton();
        bntGhiFile = new javax.swing.JButton();
        bntGiaiMa = new javax.swing.JButton();
        bntMoFile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("AES");

        aaaa.setText("User name :");

        jLabel3.setText("Password :");

        zzz.setText("Mã đăng ký :");

        jLabel5.setText("PlainText :");

        txtvanban.setColumns(20);
        txtvanban.setRows(5);
        jScrollPane1.setViewportView(txtvanban);

        txtkhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkhoaActionPerformed(evt);
            }
        });

        txtuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuserActionPerformed(evt);
            }
        });

        bntDangNhap.setText("Đăng nhập");
        bntDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntDangNhapActionPerformed(evt);
            }
        });

        bntDangKy.setText("Đăng ký");
        bntDangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntDangKyActionPerformed(evt);
            }
        });

        jLabel6.setText("CipherText :");

        txtmahoa.setColumns(20);
        txtmahoa.setRows(5);
        jScrollPane2.setViewportView(txtmahoa);

        bntMaHoa.setText("Mã hóa");
        bntMaHoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntMaHoaActionPerformed(evt);
            }
        });

        bntGhiFile.setText("GhiFile");
        bntGhiFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntGhiFileActionPerformed(evt);
            }
        });

        bntGiaiMa.setText("Giải Mã");
        bntGiaiMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntGiaiMaActionPerformed(evt);
            }
        });

        bntMoFile.setText("Mở File");
        bntMoFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntMoFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(bntDangNhap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bntDangKy)
                .addGap(61, 61, 61))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(aaaa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(zzz)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                                    .addComponent(txtkhoa)
                                    .addComponent(jScrollPane2)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(bntMaHoa)
                .addGap(18, 18, 18)
                .addComponent(bntGhiFile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bntGiaiMa)
                .addGap(18, 18, 18)
                .addComponent(bntMoFile)
                .addGap(8, 8, 8))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aaaa)
                    .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zzz)
                    .addComponent(txtkhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bntDangNhap)
                            .addComponent(bntDangKy))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntMaHoa)
                    .addComponent(bntGhiFile)
                    .addComponent(bntGiaiMa)
                    .addComponent(bntMoFile))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtkhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkhoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkhoaActionPerformed

    private void txtuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuserActionPerformed

    private void bntDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntDangNhapActionPerformed
        try{
             String user = txtuser.getText();
            String pass = txtpass.getText();
            String khoa = user + pass;
            BufferedReader br = null;
            String fileName = "D:\\AES.txt";
            br = new BufferedReader (new FileReader (fileName));
            StringBuffer sb = new StringBuffer();
            char[] ca = new char[5];
            while (br.ready())
            {
                int len = br.read(ca);
                sb.append(ca, 0, len);
                
            }
            br.close();
            System.out.println("Khoa la"+" "+sb);
            String chuoi=sb.toString();
            Boolean k=khoa.equals(chuoi);
            if(k==true)
                JOptionPane.showMessageDialog(null, "Dang nhap thanh cong");
                else
                JOptionPane.showMessageDialog(null, "Dang nhap that bai");
            txtkhoa.setText(chuoi.getBytes().toString());
            KeyGenerator keygen = KeyGenerator.getInstance("AES");
            keygen.init(128);
            secretKey = keygen.generateKey();
            
            
        } catch (NoSuchAlgorithmException ex)
        {
            
        }catch (Exception ex){}
                
    }//GEN-LAST:event_bntDangNhapActionPerformed

    private void bntDangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntDangKyActionPerformed
            try{
            String user = txtuser.getText();
            String pass = txtpass.getText();
            String khoa = user + pass;
            BufferedWriter bw = null;
            String fileName = "D:\\AES.txt";
            bw = new BufferedWriter (new FileWriter (fileName));
            bw.write(khoa);
            bw.close();
            JOptionPane.showMessageDialog(null, "Dang ky thanh cong vui long dang nhap lai");
            txtkhoa.setText(khoa.getBytes().toString());
            } catch (IOException ex){
                Logger.getLogger(AES.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_bntDangKyActionPerformed

    private void bntMaHoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntMaHoaActionPerformed
        try{
        System.out.println("Sinh khoa: "+secretKey);
        Cipher aesCipher = Cipher.getInstance("AES");
        aesCipher.init(Cipher.ENCRYPT_MODE, secretKey);
        String strData = txtvanban.getText();
        byte[] byteDataToEncrypt = strData.getBytes();
        byteCipherText = aesCipher.doFinal(byteDataToEncrypt);
        String strCipherText = Base64.getEncoder().encodeToString(byteCipherText);
        System.out.println("ma hoa dung aes la : "+strCipherText);
        txtmahoa.setText(strCipherText);
    }catch (Exception ex)
            {
            System.out.println("Loi ma hoa : "+ex);
            }
    }//GEN-LAST:event_bntMaHoaActionPerformed

    private void bntGiaiMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntGiaiMaActionPerformed
        try{
            String cipherText=txtmahoa.getText();
            txtvanban.setText(cipherText);
            Cipher aesCipher = Cipher.getInstance("AES");
            aesCipher.init(Cipher.DECRYPT_MODE, secretKey, aesCipher.getParameters());
            
            byte[] byteDecryptedText = aesCipher.doFinal(byteCipherText);
            String strDecryptedText = new String(byteDecryptedText);
            System.out.println("giai ma la"+strDecryptedText);
            txtmahoa.setText(strDecryptedText);
            
        }catch (Exception ex){
            System.out.println("Loi ma hoa : "+ex);
        }
    }//GEN-LAST:event_bntGiaiMaActionPerformed

    private void bntGhiFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntGhiFileActionPerformed
       try{
           BufferedWriter bw = null;
           String fileName = "D:\\GhiAES.txt";
           String s = txtmahoa.getText();
           bw = new BufferedWriter(new FileWriter(fileName));
           bw.write(s);
           bw.close();
           JOptionPane.showMessageDialog(null, "da ghi file D:\\ghiAES.txt");
       }catch (Exception ex){
            Logger.getLogger(AES.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_bntGhiFileActionPerformed

    private void bntMoFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntMoFileActionPerformed
        try{
           BufferedReader br = null;
           String fileName = "D:\\GhiAES.txt";
           br = new BufferedReader(new FileReader(fileName));
           StringBuffer sb = new StringBuffer();
           JOptionPane.showMessageDialog(null, "da mo file");
           char[] ca= new char[5];
           while (br.ready()){
               int len = br.read(ca);
               sb.append(ca, 0, len);
               
           }
           br.close();
           System.out.println("Du lieu la : "+" "+sb);
           String chuoi = sb.toString();
           txtvanban.setText(chuoi);
            bntGiaiMa.enable(true);
        } catch (Exception ex){
            Logger.getLogger(AES.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bntMoFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AES().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aaaa;
    private javax.swing.JButton bntDangKy;
    private javax.swing.JButton bntDangNhap;
    private javax.swing.JButton bntGhiFile;
    private javax.swing.JButton bntGiaiMa;
    private javax.swing.JButton bntMaHoa;
    private javax.swing.JButton bntMoFile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtkhoa;
    private javax.swing.JTextArea txtmahoa;
    private javax.swing.JTextField txtpass;
    private javax.swing.JTextField txtuser;
    private javax.swing.JTextArea txtvanban;
    private javax.swing.JLabel zzz;
    // End of variables declaration//GEN-END:variables
}
