package Tuan3;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.math.BigInteger;
import javax.crypto.KeyGenerator;
import javax.swing.JOptionPane;
import java.lang.Exception;
import java.security.GeneralSecurityException;
import java.security.NoSuchAlgorithmException;
import java.util.Base64;
import javax.crypto.Cipher;
import javax.crypto.SecretKey;
import java.util.Base64;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Mingo
 */
public class FormRSA extends javax.swing.JFrame {

    /**
     * Creates new form FormRSA
     */
    public FormRSA() {
        initComponents();
    }
    
    RSA rsa = new RSA(8);

    String plainText;
    String nhash;
    BigInteger[] ciphertext = null;
    BigInteger n = null;
    BigInteger d = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtPlain = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtCipher = new javax.swing.JTextArea();
        txtEncrypt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtDecrypt = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPasswd = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Roboto Mono SemiBold", 0, 16)); // NOI18N
        jLabel3.setText("Plain Text");

        txtPlain.setColumns(20);
        txtPlain.setFont(new java.awt.Font("Roboto Mono Light", 0, 14)); // NOI18N
        txtPlain.setRows(5);
        jScrollPane2.setViewportView(txtPlain);

        jLabel4.setFont(new java.awt.Font("Roboto Mono SemiBold", 0, 16)); // NOI18N
        jLabel4.setText("CipherText");

        txtCipher.setColumns(20);
        txtCipher.setFont(new java.awt.Font("Roboto Mono Light", 0, 14)); // NOI18N
        txtCipher.setRows(5);
        jScrollPane3.setViewportView(txtCipher);

        txtEncrypt.setFont(new java.awt.Font("Roboto Mono SemiBold", 0, 14)); // NOI18N
        txtEncrypt.setText("ENCRYPT");
        txtEncrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEncryptActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto Mono SemiBold", 0, 18)); // NOI18N
        jLabel1.setText("RSA");

        txtDecrypt.setFont(new java.awt.Font("Roboto Mono SemiBold", 0, 14)); // NOI18N
        txtDecrypt.setText("DECRYPT");
        txtDecrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDecryptActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Roboto Mono SemiBold", 0, 16)); // NOI18N
        jLabel2.setText("Password");

        jScrollPane1.setViewportView(txtPasswd);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane3)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(188, 188, 188)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(17, 17, 17))
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(txtEncrypt)
                .addGap(79, 79, 79)
                .addComponent(txtDecrypt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEncrypt)
                    .addComponent(txtDecrypt))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEncryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEncryptActionPerformed
        try {
            plainText = txtPlain.getText();
            n = rsa.getN();
            d = rsa.getD();
            ciphertext = rsa.encrypt(plainText);
            StringBuffer bf = new StringBuffer();
            for(int i = 0; i < ciphertext.length; i++){
                bf.append(ciphertext[i].toString(16).toUpperCase());
                if(i != ciphertext.length -1)
                System.out.print("");
            }

            String message = bf.toString();
            txtCipher.setText(message);
        }
        catch(Exception ex) {}
    }//GEN-LAST:event_txtEncryptActionPerformed

    private void txtDecryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDecryptActionPerformed
        String dhash = rsa.decrypt(ciphertext, d, n);
        txtPlain.setText(dhash);
    }//GEN-LAST:event_txtDecryptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormRSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormRSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormRSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormRSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormRSA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea txtCipher;
    private javax.swing.JButton txtDecrypt;
    private javax.swing.JButton txtEncrypt;
    private javax.swing.JTextPane txtPasswd;
    private javax.swing.JTextArea txtPlain;
    // End of variables declaration//GEN-END:variables
}
